# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbce03c207fbe6cb70a4f40152ee6dc1ca1c035d41819b6e85c736d96d9c37c4f107dd591b829785370067c82ec21421a38f3444dbe53240910957068b807c6d

test:
  secret_key_base: 09b395d9d622026fa9b70243255fb4b02371012e1a85176e2a5000985345a3759e71033f3e661b8a57ae8349474b72158db2a209853b1fd83eaf1489b589f087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
